version: '3'

services:
  xtree_app:
    container_name: xtree_app
    build: .
    tty: true
    ports:
      - 3333:3333
      - 9229:9229
    networks:
      - app-network
    volumes:
      - .:/home/node/app

  xtree_postgres:
    container_name: xtree_postgres
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql

networks:
  app-network:
    driver: bridge
